### ISSUE TITLE
Choose a stack

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#1]
The produced website must be static, accessible and white label (so other organization could use it). Otherwise feel free to use any kind of tools who wish, let discuss about it.

**Comment by hgwood** [comment]
Gatsby might be a good fit.

**Comment by christopherkade** [comment]
> Gatsby might be a good fit.

By researching Gatsby I found its Vue counterpart called [Gridsome](https://gridsome.org/), has anyone had any experience dealing with it?
 
For Gatsby, I've personally never had the opportunity to use it but it seems like a great fit.

**Comment by frinyvonnick** [comment]
Gatsby works well I used it on a mission and for the NantesJS website. Gridsome seems to have the same features so nice alternative 👍

**Comment by mfrachet** [comment]
I like the gatsby idea, easy to setup, many tools builtin, some cool plugins

**Comment by kefranabg** [comment]
Gridsome seems to be a young project with a small community :/ (right now). [Nuxt.js](https://fr.nuxtjs.org/) provides same features, (jamstack architecture ...) and is well known from the vue.js community with a strong support

**Comment by ripoul** [comment]
> (so other organization could use it)
Does that mean you will scan only the public repos ?

**Comment by frinyvonnick** [comment]
@ripoul, It means other organizations can make their own instance with customisation options for theming, images an so on :smile:

**Comment by frinyvonnick** [comment]
Here is a poll to choose which tool to use for frontend https://doodle.com/poll/wyprv69ras4gev5i

**Comment by frinyvonnick** [comment]
So it will be Gatsby for frontend ! Thanks all for your participation 👏 I will init a fresh install of gatsby 😉
