### ISSUE TITLE
Set up a CI/CD

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#10]
Once the stack has been decided (#1) it would be nice to have a CI that ensures the website builds well and a CD to have a demo url. Which tools to use to accomplish this ?

**Comment by hgwood** [comment]
We have expertise with CircleCI. For a static website, Google Cloud App Engine is a good choice and it's free.

**Comment by frinyvonnick** [comment]
Github pages is also a good choice for static website 😄

**Comment by bpetetot** [comment]
Netlify is also really easy to use and free

**Comment by kefranabg** [comment]
I also think that Netlify is a good option. It also opens [live previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) on users pull requests which could be really cool to easily inspect new features from PRs

**Comment by frinyvonnick** [comment]
Here a poll to choose an hosting solution/cloud provider https://doodle.com/poll/ma7gcvsvmh9hnrmg

**Comment by frinyvonnick** [comment]
So the hosting solution/cloud provider will be [netlify](https://www.netlify.com/). @hgwood proposed CircleCI there is also TravisCI. Other ideas ?

**Comment by tbetous** [comment]
I have already set a CircleCi with a Netlify for a side project. It can be done easily. I don't know much TravisCI, but if we go with CircleCI I volunteer for this task.

**Comment by frinyvonnick** [comment]
Ok so CircleCI seems to be the solution ! 🎉
