### ISSUE TITLE
Add CookieBot for GDPR compliance

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#18]
We must add [CookieBot](https://www.cookiebot.com/en/) for GDPR compliance needed for #19.

**Comment by frinyvonnick** [comment]
I'm thinking about making a [Gatsby plugin](https://www.gatsbyjs.org/docs/how-plugins-work/) for [CookieBot](https://github.com/prinzstani/CookieBot).

**Comment by bpetetot** [comment]
Done in #75
