### ISSUE TITLE
Add quality tools

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#23]
We must add quality related tools for our code like `eslint`, `stylelint` that can run in CI. We can also add tools for development like `Prettier`. Which tools do you want to use for this purpose ?

**Comment by Ked57** [comment]
Prettier can also run in the CI to check formatting :+1: I could do a PR if you want

**Comment by frinyvonnick** [comment]
Sure 👍, but we will wait a bit till the team has the opportunity to propose alternatives and choose which tools to use 😄

**Comment by kefranabg** [comment]
Prettier + Eslint = ❤️

**Comment by bpetetot** [comment]
*An other quality tool:*
Greenkeeper is also very useful to keep the project up-to-date

**Comment by kefranabg** [comment]
[bundlesize](https://github.com/siddharthkp/bundlesize) is great. It would help us to control our bundles sizes. It's like webpack bundle analyzer, and can be ran from the CI.

**Comment by charlyx** [comment]
@bpetetot Greenkeeper is cool but can be a real pain in the ass if dependencies don't get updated regularly.

**Comment by charlyx** [comment]
What do you think of [lighthousebot](https://github.com/GoogleChromeLabs/lighthousebot)?

**Comment by kefranabg** [comment]
@charlyx Lightousebot only works with CircleCI :/

**Comment by charlyx** [comment]
@kefranabg you mean TravisCI? I'm sure with can use it using the CLI 😄 
I believe @bpetetot has been using it at TheFork?

**Comment by bpetetot** [comment]
Yes you can use lighthouse as a CLI

**Comment by frinyvonnick** [comment]
Here is the doodle to choose quality tools https://doodle.com/poll/gbgrss3wuzn849cf. Options that have a majority of votes will be choosen. That's a start we will add other tools as we need it 😄.

**Comment by frinyvonnick** [comment]
Almost everybody agreed about Eslint, Prettier, Greenkeeper and Bundlesize. I'll open issues to set up these tools. 

We will keep lighthouse in mind for a second time if that's ok for everybody :+1:
