### ISSUE TITLE
Copy data into the project

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#27]
Import `stats.json` file made with [github-insights](https://github.com/Zenika/github-insights/pull/5)

**Comment by christopherkade** [comment]
Would it imply moving the github-insights project to this repo right away or simply grabbing the generated file and putting it into a `data` folder for later use?

**Comment by bpetetot** [comment]
For now, this is simply grabbing the generated file and putting it into a data folder. Of course, this is a temporary solution to have a quick MVP. Later, we will automate the data grabbing
