### ISSUE TITLE
Choose a visual identity

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#3]
We are searching for someone motivated in providing a visual model for the website.

Inspiration: https://octoverse.github.com/projects

**Comment by christopherkade** [comment]
There has been talks of creating a design system for Zenika, should we stick to it or would the platform be independent in its design?

**Comment by frinyvonnick** [comment]
This project needs to be white labelled so other organizations could use it but we could customize Zenika's instance so it follows this "design system" 👍 

Who can tell us more about this @christopherkade ?

**Comment by christopherkade** [comment]
We'll have a new art director at AYA in May and it seems like she'll be the one managing the design system project. 

It may be too far off to rely on it, especially since we want the design to be white labelled. So the safest call would probably be to create a visual identity from scratch.

**Comment by tbetous** [comment]
For the future template we need to be netlify compliant and include one of these badges : https://www.netlify.com/press/#badges

**Comment by frinyvonnick** [comment]
Closed by #41
