### ISSUE TITLE
Global informations

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#4]
- [x] Number of members
- [x] Number of repositories on which members worked
- [ ] Number of pull requests made by members

**Comment by frinyvonnick** [comment]
Closed in favor of #25

**Comment by christopherkade** [comment]
> Number of pull requests made by members

I don't believe we currently have that data in our `stats` file. Github Insights does not extract it yet.

**Comment by frinyvonnick** [comment]
Sure we need to improve Github insights to make it possible 😄
