### ISSUE TITLE
Replace stars by GitHub star button

### ISSUE THREAD

**Issue by frinyvonnick** [zenika-open-source/insights-website#64]

**Comment by christopherkade** [comment]
Just to be sure I understand, you mean going from:

<img width="84" alt="Screenshot 2019-10-14 at 10 52 48" src="https://user-images.githubusercontent.com/15229355/66739366-d0e61c00-ee70-11e9-86a8-223e3b1b8030.png">

to

<img width="107" alt="Screenshot 2019-10-14 at 10 53 00" src="https://user-images.githubusercontent.com/15229355/66739373-d3e10c80-ee70-11e9-93d6-fa01f7e768e5.png"> ?

Thanks in advance !

**Comment by crisgit** [comment]
Hi, as the site uses React, so you can use Preact which is fast.
Follow the code below as an example in the site docs:

export default class Stars extends Component {
    async componentDidMount() {
        let stars = await githubStars(this.props.repo);
        this.setState({ stars });
    }
    render({ repo }, { stars=0 }) {
        let url = \`https://github.com/${repo}\`;
        return (
            <a href={url} class="stars">
                ⭐️ {stars} Stars
            </a>
        );
    }
}

More info: https://preactjs.com/

**Comment by crisgit** [comment]
Hi, as the site uses React, so you can use Preact which is fast.
Follow the code below as an example in the site docs:

export default class Stars extends Component {
    async componentDidMount() {
        let stars = await githubStars(this.props.repo);
        this.setState({ stars });
    }
    render({ repo }, { stars=0 }) {
        let url = \`https://github.com/${repo}\`;
        return (
            <a href={url} class="stars">
                ⭐️ {stars} Stars
            </a>
        );
    }
}

More info: https://preactjs.com/

**Comment by frinyvonnick** [comment]
This issue was more about using the implementation provided by GitHub: https://buttons.github.io/

There is a react implementation for these button:

```jsx
import GitHubButton from 'react-github-btn'
```

@crisgit is Preact compatible with GatsbyJS ?

**Comment by crisgit** [comment]
In gatsby is by plugin preact. This information with the explanation you can see:

**https://www.gatsbyjs.org/packages/gatsby-plugin-preact/**

**Comment by crisgit** [comment]
In GatsbyJS is by plugin preact. This information with the explanation you can see:

**https://www.gatsbyjs.org/packages/gatsby-plugin-preact/**

**Comment by frinyvonnick** [comment]
Thank you for the information @crisgit 👍

**Comment by bpetetot** [comment]
Done
